'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { getFingerprint, signInWithFirebase, signInWithPasskey } from '@/lib/auth-client'

export default function LoginPage() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [mode, setMode] = useState<'firebase'|'passkey'>('firebase'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { const fingerprint = await getFingerprint(); const result = mode === 'firebase' ? await signInWithFirebase(email, password) : await signInWithPasskey(email); localStorage.setItem('mediflow_token', result.accessToken); localStorage.setItem('mediflow_fingerprint', fingerprint.visitorId); window.location.href = result.user.role === 'owner' ? '/owner/dashboard' : result.user.role === 'employee' ? '/employee/dashboard' : '/customer/dashboard' } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to sign in') } finally { setBusy(false) } }
  return <main className="auth-page"><div className="auth-art"><Link href="/" className="brand"><span className="brand-mark">✦</span><span>mediflow</span></Link><div><div className="eyebrow">NORTHSTAR PHARMACY</div><h1>Care works better<br/><em>in rhythm.</em></h1><p>A secure workspace for owners, employees, and customers.</p></div><span className="auth-art-footer">Firebase · FingerprintJS · WebAuthn</span></div><section className="auth-card"><div className="eyebrow">SECURE ACCESS</div><h2>Welcome back</h2><p>Sign in to enter your dedicated Mediflow room.</p><div className="auth-tabs"><button className={mode==='firebase'?'selected':''} onClick={()=>setMode('firebase')}>Firebase</button><button className={mode==='passkey'?'selected':''} onClick={()=>setMode('passkey')}>Passkey</button></div><form onSubmit={submit}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@pharmacy.com"/></label>{mode==='firebase' && <label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/></label>}{message && <div className="auth-error">{message}</div>}<button className="primary auth-submit" disabled={busy}>{busy ? 'Verifying…' : mode==='firebase' ? 'Continue securely →' : 'Use passkey →'}</button></form><div className="auth-note">Your device is verified with FingerprintJS on sign-in.</div></section></main> }
